spring:
  application:
    name: Move API
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: dev
    password: devpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

project:
  poster: poster/

base:
  url: "http://localhost:8080"